### ISSUE TITLE
Clean up obsolete branches and milestones

### ISSUE THREAD

**Issue by t-sommer** [modelica/fmi-standard#2015]
Obsolete branches

- [ ] fix-fmi2-bugfix-version
- [ ] universal-architecture
- [ ] bump-fmi3-version
- [ ] fix/interface-types

Obsolete milestones

- [x] v2.0.4
- [x] v2.0.5
- [x] v3.0
- [x] v3.0.1
- [x] v3.0.2

**Comment by chrbertsch** [comment]
We closed some milestones, and @pmai will delete obsolte branches.
